### ISSUE TITLE
Resume

### ISSUE THREAD

**Issue by satyendrakannaujiya** [gauravmehla/ama#1]
hii ,
I am satyendra kannaujiya, MCA  second year student on NIT Allahabad.
Can you send me your resume so that I can edit it in my way plzzz.
thank in advance.

email-id--satyendra250896@gmail.com

**Comment by gauravmehla** [comment]
@satyendrakannaujiya  just have a look at https://novoresume.com/

**Comment by satyendrakannaujiya** [comment]
@gauravmehla thanks
