### ISSUE TITLE
How to find projects on Github to contribute

### ISSUE THREAD

**Issue by vulchivijayakumar** [gauravmehla/ama#3]
Hi gaurav,

Where do i found github open source projects to contribute myself at free time.

**Comment by gauravmehla** [comment]
### How to find projects on Github to contribute

![](https://cdn-images-1.medium.com/max/1200/1*0nhcZ0ZZgaEpQ-aps6UNDg.png)

Github is full of open-source projects. I agree that it is very hard in the beginning to search for a good open-source project to contribute but with time you will learn that the approach that many developers use to look for their first open-source project is not actually the right way to look for. Its very hard to find a open-source project in which you can contribute by just searching on Google and Github. I also did the same mistake when I started my professional career. So, I would suggest that we have to first change our approach to find a good open-source project.

First, finding a good open-source project which will be suitable for you can take longer than you think. It can even take months to get one but you have to be patient.

Second, start looking for people who has same skill set or the skill set you want to add in yourself on Github. You will definitely find one in some time and then you can start looking for projects on which that person is worked on. Then start reading their code, read wiki and fix some issues. If you are facing some trouble in understanding the project, you can directly contact the maintainers and owners of that repo. 

Third, as being a developer, we usually use a lot of open-source libraries in our projects. You can contribute to them if you really want to build some serious skills in yourself. But beware, these projects can have very huge codebase and you have to be consistent and patient to first understand the flow of the project.

Last, start following "full-time open-sourceres". I started my career by getting motivation from [Sindre Sorhus](https://github.com/sindresorhus). I went through most of his repositories and learned a lot about structuring code and cool hacks that usually developers use while coding. So, I would suggest keep looking for a mentor.

#### If you are beginner, you can have a look at:

https://github.com/MunGell/awesome-for-beginners
https://github.com/sarthology/searchDetox
https://github.com/gauravmehla/Remaining/

#### If you have some serious skills then

https://github.com/explore

#### Suggestion
As you are also a developer, you must have used any open-source library which you also liked very much and curious to know more about it. Start investing you time by first learning about that code flow of that project. Then go to the issues section and try to fix any issue. This is the best way to contribute to open-source community. Don't go for easy way like contributing in readme's ( which I went for ) but as we have to go very far we can't just keep contributing to readme's. It is good only to learn that how we contribute in open-source like 
1. First fork the repo
2. Do the changes
3. Create a PR

That's It. 

If you do not know how to do this, [Contribute to this repo](https://github.com/sindresorhus/amas) and you will know how this process works.

I think I have explained pretty much.

Thanks

#firstcontribution
